// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1N45-C0rwQdUD5XQk2Nqa2Bioh7uC-so',
    appId: '1:18555773657:web:d45f67b0c4e212362214c8',
    messagingSenderId: '18555773657',
    projectId: 'movieapp-86736',
    authDomain: 'movieapp-86736.firebaseapp.com',
    storageBucket: 'movieapp-86736.appspot.com',
    measurementId: 'G-WFREY8GGPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnpJHKdM1YXBGS6dmhkT-Aoxvtq90cNo8',
    appId: '1:18555773657:android:36b517f5bd9efd072214c8',
    messagingSenderId: '18555773657',
    projectId: 'movieapp-86736',
    storageBucket: 'movieapp-86736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClasvouyIiG1W9gPwr-ob_tcudp_0mexs',
    appId: '1:18555773657:ios:a52a4068532c7fba2214c8',
    messagingSenderId: '18555773657',
    projectId: 'movieapp-86736',
    storageBucket: 'movieapp-86736.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClasvouyIiG1W9gPwr-ob_tcudp_0mexs',
    appId: '1:18555773657:ios:a52a4068532c7fba2214c8',
    messagingSenderId: '18555773657',
    projectId: 'movieapp-86736',
    storageBucket: 'movieapp-86736.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1N45-C0rwQdUD5XQk2Nqa2Bioh7uC-so',
    appId: '1:18555773657:web:994f4e5dbd1d705a2214c8',
    messagingSenderId: '18555773657',
    projectId: 'movieapp-86736',
    authDomain: 'movieapp-86736.firebaseapp.com',
    storageBucket: 'movieapp-86736.appspot.com',
    measurementId: 'G-JXP22GTP0T',
  );
}
